files = [ "wrc_lm32.vhd", 
					"lm32_cpu.v", 
					"lm32_addsub.v", 
					"lm32_top.v",
					"lm32_instruction_unit.v",
					"lm32_decoder.v",
					"lm32_load_store_unit.v",
					"lm32_adder.v",
					"lm32_logic_op.v",
					"lm32_shifter.v",
					"lm32_multiplier.v",
					"lm32_interrupt.v",
					"lm32_dp_ram.v",
					"lm32_debug.v",
					"lm32_jtag.v",
					"jtag_wb.v"
					 ];