files = [
  "eca.vhd",
  "eca_adder.vhd",
  "eca_channel.vhd",
  "eca_gpio_channel.vhd",
  "eca_offset.vhd",
  "eca_pkg.vhd",
  "eca_sdp.vhd",
  "eca_search.vhd",
  "eca_tdp.vhd",
  "eca_walker.vhd",
  "eca_wb_channel.vhd",
  "eca_wb_event.vhd",
  "eca_wr_time.vhd",
  "wr_eca.vhd"]
