onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /main/DUT/PERIPH/rst_n_i
add wave -noupdate /main/DUT/PERIPH/rst_ext_n_i
add wave -noupdate /main/DUT/rst_net_n
add wave -noupdate /main/DUT/rst_wrc_n
#add wave -noupdate /main/DUT/PERIPH/sysc_regs_o.rstr_hrst_wr_o #add wave -noupdate /main/DUT/PERIPH/sysc_regs_o.rstr_hrst_o
#add wave -noupdate /main/DUT/PERIPH/sysc_regs_o.gpsr_net_rst_o
#add wave -noupdate /main/DUT/PERIPH/slave_i(0).adr
#add wave -noupdate /main/DUT/PERIPH/slave_i(0).dat
#add wave -noupdate /main/DUT/PERIPH/slave_i(0).cyc
#add wave -noupdate /main/DUT/PERIPH/slave_i(0).stb
#add wave -noupdate /main/DUT/PERIPH/slave_o(0).dat
#add wave -noupdate /main/DUT/PERIPH/slave_o(0).ack
add wave -noupdate /main/DUT/PERIPH/SYSCON/wr_int
add wave -noupdate /main/DUT/PERIPH/sysc_regs_o 
add wave -noupdate /main/DUT/PERIPH/sysc_regs_i 

add wave -divider LM32
add wave -noupdate /main/DUT/rst_wrc_n

add wave -noupdate /main/DUT/cbar_slave_i(1).cyc  
add wave -noupdate /main/DUT/cbar_slave_i(1).stb   
add wave -noupdate /main/DUT/cbar_slave_i(1).we    
add wave -noupdate /main/DUT/cbar_slave_i(1).adr   
add wave -noupdate /main/DUT/cbar_slave_o(1).dat   
add wave -noupdate /main/DUT/cbar_slave_o(1).ack   

add wave -noupdate /main/DUT/cbar_slave_i(0).cyc 
add wave -noupdate /main/DUT/cbar_slave_i(0).stb 
add wave -noupdate /main/DUT/cbar_slave_i(0).we  
add wave -noupdate /main/DUT/cbar_slave_i(0).adr 
add wave -noupdate /main/DUT/cbar_slave_i(0).dat 
add wave -noupdate /main/DUT/cbar_slave_o(0).dat 
add wave -noupdate /main/DUT/cbar_slave_o(0).ack 

add wave -noupdate /main/DUT/lm32_irq_slv

add wave -divider PERIPH
add wave -noupdate /main/DUT/cbar_master_o(1).cyc
add wave -noupdate /main/DUT/cbar_master_o(1).stb 
add wave -noupdate /main/DUT/cbar_master_o(1).we
add wave -noupdate /main/DUT/PERIPH/UART/U_Wrapped_UART/wb_cyc_i 
add wave -noupdate /main/DUT/PERIPH/UART/U_Wrapped_UART/wb_stb_i 
add wave -noupdate /main/DUT/PERIPH/UART/U_Wrapped_UART/wb_we_i 
add wave -noupdate /main/DUT/PERIPH/UART/U_Wrapped_UART/wb_ack_o 
add wave -noupdate /main/DUT/PERIPH/UART/U_Wrapped_UART/wb_stall_o 
add wave -noupdate /main/DUT/PERIPH/UART/U_Wrapped_UART/wb_adr_i 
add wave -noupdate /main/DUT/PERIPH/UART/U_Wrapped_UART/wb_dat_i 
add wave -noupdate /main/DUT/PERIPH/UART/U_Wrapped_UART/wb_dat_o 
add wave -noupdate /main/DUT/uart_rxd_i
add wave -noupdate /main/DUT/uart_txd_o
add wave -noupdate /main/DUT/periph/uart/u_wrapped_uart/u_wb_slave/regs_i.sr_tx_busy_i

add wave -divider MINIC
add wave -noupdate /main/DUT/minic_wb_in
add wave -noupdate /main/DUT/minic_wb_out
add wave -noupdate /main/DUT/MINI_NIC/wb_i
add wave -noupdate /main/DUT/MINI_NIC/wb_o 
add wave -noupdate /main/DUT/MINI_NIC/U_Wrapped_Minic/ntx_state
add wave -noupdate /main/DUT/MINI_NIC/U_Wrapped_Minic/nrx_state
add wave -noupdate /main/DUT/MINI_NIC/U_Wrapped_Minic/regs_out.mcr_tx_start_o
add wave -noupdate /main/DUT/MINI_NIC/U_Wrapped_Minic/regs_out.mcr_rx_en_o
add wave -noupdate /main/DUT/MINI_NIC/U_Wrapped_Minic/regs_out.mcr_rx_class_o
add wave -noupdate /main/DUT/MINI_NIC/U_Wrapped_Minic/regs_out.tx_addr_o 
add wave -noupdate /main/DUT/xwr_mini_nic_1/U_Wrapped_Minic/regs_out.tx_addr_load_o
add wave -noupdate /main/DUT/mnic_mem_addr_o
add wave -noupdate /main/DUT/mnic_mem_wr_o
add wave -noupdate /main/DUT/mnic_mem_data_o
add wave -noupdate /main/DUT/mnic_mem_data_i 
add wave -noupdate /main/DUT/dpram_wbb_i
add wave -noupdate /main/DUT/dpram_wbb_o

add wave -divider ENDPOINT
add wave -noupdate /main/DUT/U_Endpoint/rst_n_i
#add wave -noupdate /main/DUT/U_Endpoint/g_interface_mode
#add wave -noupdate /main/DUT/U_Endpoint/g_address_granularity
#add wave -noupdate /main/DUT/U_Endpoint/g_simulation
#add wave -noupdate /main/DUT/U_Endpoint/g_pcs_16bit
#add wave -noupdate /main/DUT/U_Endpoint/g_rx_buffer_size
#add wave -noupdate /main/DUT/U_Endpoint/g_with_rx_buffer
#add wave -noupdate /main/DUT/U_Endpoint/g_with_flow_control
#add wave -noupdate /main/DUT/U_Endpoint/g_with_timestamper
#add wave -noupdate /main/DUT/U_Endpoint/g_with_dpi_classifier
#add wave -noupdate /main/DUT/U_Endpoint/g_with_vlans
#add wave -noupdate /main/DUT/U_Endpoint/g_with_rtu
#add wave -noupdate /main/DUT/U_Endpoint/g_with_leds
add wave -noupdate /main/DUT/U_Endpoint/clk_ref_i
add wave -noupdate /main/DUT/U_Endpoint/clk_sys_i
add wave -noupdate /main/DUT/U_Endpoint/rst_n_i
add wave -noupdate /main/DUT/U_Endpoint/pps_csync_p1_i
add wave -noupdate /main/DUT/U_Endpoint/phy_rst_o
add wave -noupdate /main/DUT/U_Endpoint/phy_loopen_o
add wave -noupdate /main/DUT/U_Endpoint/phy_enable_o
add wave -noupdate /main/DUT/U_Endpoint/phy_syncen_o
add wave -noupdate /main/DUT/U_Endpoint/phy_ref_clk_i
add wave -noupdate /main/DUT/U_Endpoint/phy_tx_data_o
add wave -noupdate /main/DUT/U_Endpoint/phy_tx_k_o
add wave -noupdate /main/DUT/U_Endpoint/phy_tx_disparity_i
add wave -noupdate /main/DUT/U_Endpoint/phy_tx_enc_err_i
add wave -noupdate /main/DUT/U_Endpoint/phy_rx_data_i
add wave -noupdate /main/DUT/U_Endpoint/phy_rx_clk_i
add wave -noupdate /main/DUT/U_Endpoint/phy_rx_k_i
add wave -noupdate /main/DUT/U_Endpoint/phy_rx_enc_err_i
add wave -noupdate /main/DUT/U_Endpoint/phy_rx_bitslide_i
add wave -noupdate /main/DUT/U_Endpoint/gmii_tx_clk_i
add wave -noupdate /main/DUT/U_Endpoint/gmii_txd_o
add wave -noupdate /main/DUT/U_Endpoint/gmii_tx_en_o
add wave -noupdate /main/DUT/U_Endpoint/gmii_tx_er_o
add wave -noupdate /main/DUT/U_Endpoint/gmii_rx_clk_i
add wave -noupdate /main/DUT/U_Endpoint/gmii_rxd_i
add wave -noupdate /main/DUT/U_Endpoint/gmii_rx_er_i
add wave -noupdate /main/DUT/U_Endpoint/gmii_rx_dv_i
add wave -noupdate /main/DUT/U_Endpoint/src_o
add wave -noupdate /main/DUT/U_Endpoint/src_i
add wave -noupdate /main/DUT/U_Endpoint/snk_o
add wave -noupdate /main/DUT/U_Endpoint/snk_i
add wave -noupdate /main/DUT/U_Endpoint/txtsu_port_id_o
add wave -noupdate /main/DUT/U_Endpoint/txtsu_frame_id_o
add wave -noupdate /main/DUT/U_Endpoint/txtsu_tsval_o
add wave -noupdate /main/DUT/U_Endpoint/txtsu_valid_o
add wave -noupdate /main/DUT/U_Endpoint/txtsu_ack_i
add wave -noupdate /main/DUT/U_Endpoint/rtu_full_i
add wave -noupdate /main/DUT/U_Endpoint/rtu_almost_full_i
add wave -noupdate /main/DUT/U_Endpoint/rtu_rq_strobe_p1_o
add wave -noupdate /main/DUT/U_Endpoint/rtu_rq_smac_o
add wave -noupdate /main/DUT/U_Endpoint/rtu_rq_dmac_o
add wave -noupdate /main/DUT/U_Endpoint/rtu_rq_vid_o
add wave -noupdate /main/DUT/U_Endpoint/rtu_rq_has_vid_o
add wave -noupdate /main/DUT/U_Endpoint/rtu_rq_prio_o
add wave -noupdate /main/DUT/U_Endpoint/rtu_rq_has_prio_o
add wave -noupdate /main/DUT/U_Endpoint/wb_i
add wave -noupdate /main/DUT/U_Endpoint/wb_o
add wave -noupdate /main/DUT/U_Endpoint/led_link_o
add wave -noupdate /main/DUT/U_Endpoint/led_act_o
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {67408050000 fs} 0}
configure wave -namecolwidth 183
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {28718575420 fs} {159968575420 fs}
