onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /main/DUT/U_Endpoint/g_interface_mode
add wave -noupdate /main/DUT/U_Endpoint/g_address_granularity
add wave -noupdate /main/DUT/U_Endpoint/g_simulation
add wave -noupdate /main/DUT/U_Endpoint/g_pcs_16bit
add wave -noupdate /main/DUT/U_Endpoint/g_rx_buffer_size
add wave -noupdate /main/DUT/U_Endpoint/g_with_rx_buffer
add wave -noupdate /main/DUT/U_Endpoint/g_with_flow_control
add wave -noupdate /main/DUT/U_Endpoint/g_with_timestamper
add wave -noupdate /main/DUT/U_Endpoint/g_with_dpi_classifier
add wave -noupdate /main/DUT/U_Endpoint/g_with_vlans
add wave -noupdate /main/DUT/U_Endpoint/g_with_rtu
add wave -noupdate /main/DUT/U_Endpoint/g_with_leds
add wave -noupdate /main/DUT/U_Endpoint/clk_ref_i
add wave -noupdate /main/DUT/U_Endpoint/clk_sys_i
add wave -noupdate /main/DUT/U_Endpoint/rst_n_i
add wave -noupdate /main/DUT/U_Endpoint/pps_csync_p1_i
add wave -noupdate /main/DUT/U_Endpoint/phy_rst_o
add wave -noupdate /main/DUT/U_Endpoint/phy_loopen_o
add wave -noupdate /main/DUT/U_Endpoint/phy_enable_o
add wave -noupdate /main/DUT/U_Endpoint/phy_syncen_o
add wave -noupdate /main/DUT/U_Endpoint/phy_ref_clk_i
add wave -noupdate /main/DUT/U_Endpoint/phy_tx_data_o
add wave -noupdate /main/DUT/U_Endpoint/phy_tx_k_o
add wave -noupdate /main/DUT/U_Endpoint/phy_tx_disparity_i
add wave -noupdate /main/DUT/U_Endpoint/phy_tx_enc_err_i
add wave -noupdate /main/DUT/U_Endpoint/phy_rx_data_i
add wave -noupdate /main/DUT/U_Endpoint/phy_rx_clk_i
add wave -noupdate /main/DUT/U_Endpoint/phy_rx_k_i
add wave -noupdate /main/DUT/U_Endpoint/phy_rx_enc_err_i
add wave -noupdate /main/DUT/U_Endpoint/phy_rx_bitslide_i
add wave -noupdate /main/DUT/U_Endpoint/gmii_tx_clk_i
add wave -noupdate /main/DUT/U_Endpoint/gmii_txd_o
add wave -noupdate /main/DUT/U_Endpoint/gmii_tx_en_o
add wave -noupdate /main/DUT/U_Endpoint/gmii_tx_er_o
add wave -noupdate /main/DUT/U_Endpoint/gmii_rx_clk_i
add wave -noupdate /main/DUT/U_Endpoint/gmii_rxd_i
add wave -noupdate /main/DUT/U_Endpoint/gmii_rx_er_i
add wave -noupdate /main/DUT/U_Endpoint/gmii_rx_dv_i
add wave -noupdate /main/DUT/U_Endpoint/src_o
add wave -noupdate /main/DUT/U_Endpoint/src_i
add wave -noupdate /main/DUT/U_Endpoint/snk_o
add wave -noupdate /main/DUT/U_Endpoint/snk_i
add wave -noupdate /main/DUT/U_Endpoint/txtsu_port_id_o
add wave -noupdate /main/DUT/U_Endpoint/txtsu_frame_id_o
add wave -noupdate /main/DUT/U_Endpoint/txtsu_tsval_o
add wave -noupdate /main/DUT/U_Endpoint/txtsu_valid_o
add wave -noupdate /main/DUT/U_Endpoint/txtsu_ack_i
add wave -noupdate /main/DUT/U_Endpoint/rtu_full_i
add wave -noupdate /main/DUT/U_Endpoint/rtu_almost_full_i
add wave -noupdate /main/DUT/U_Endpoint/rtu_rq_strobe_p1_o
add wave -noupdate /main/DUT/U_Endpoint/rtu_rq_smac_o
add wave -noupdate /main/DUT/U_Endpoint/rtu_rq_dmac_o
add wave -noupdate /main/DUT/U_Endpoint/rtu_rq_vid_o
add wave -noupdate /main/DUT/U_Endpoint/rtu_rq_has_vid_o
add wave -noupdate /main/DUT/U_Endpoint/rtu_rq_prio_o
add wave -noupdate /main/DUT/U_Endpoint/rtu_rq_has_prio_o
add wave -noupdate /main/DUT/U_Endpoint/wb_i
add wave -noupdate /main/DUT/U_Endpoint/wb_o
add wave -noupdate /main/DUT/U_Endpoint/led_link_o
add wave -noupdate /main/DUT/U_Endpoint/led_act_o
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {67408050000 fs} 0}
configure wave -namecolwidth 183
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {28718575420 fs} {159968575420 fs}
