---------------------------------------------------------------------------------------
-- Title          : Wishbone slave core for OBP
---------------------------------------------------------------------------------------
-- File           : obp_wbgen2_pkg.vhd
-- Author         : auto-generated by wbgen2 from obp_wb_slave.wb
-- Created        : Fri Feb 27 10:07:37 2015
-- Standard       : VHDL'87
---------------------------------------------------------------------------------------
-- THIS FILE WAS GENERATED BY wbgen2 FROM SOURCE FILE obp_wb_slave.wb
-- DO NOT HAND-EDIT UNLESS IT'S ABSOLUTELY NECESSARY!
---------------------------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

package obp_wbgen2_pkg is
  
  
  -- Input registers (user design -> WB slave)
  
  type t_obp_in_registers is record
    cflags_prog_i                            : std_logic;
    end record;
  
  constant c_obp_in_registers_init_value: t_obp_in_registers := (
    cflags_prog_i => '0'
    );
    
    -- Output registers (WB slave -> user design)
    
    type t_obp_out_registers is record
      n_prog_w_n_prog_w_o                      : unsigned(31 downto 0);
      cflags_stp_o                             : std_logic;
      end record;
    
    constant c_obp_out_registers_init_value: t_obp_out_registers := (
      n_prog_w_n_prog_w_o => (others => '0'),
      cflags_stp_o => '0'
      );
    function "or" (left, right: t_obp_in_registers) return t_obp_in_registers;
    function f_x_to_zero (x:std_logic) return std_logic;
    function f_x_to_zero (x:std_logic_vector) return std_logic_vector;
end package;

package body obp_wbgen2_pkg is
function f_x_to_zero (x:std_logic) return std_logic is
begin
if x = '1' then
return '1';
else
return '0';
end if;
end function;
function f_x_to_zero (x:std_logic_vector) return std_logic_vector is
variable tmp: std_logic_vector(x'length-1 downto 0);
begin
for i in 0 to x'length-1 loop
if(x(i) = 'X' or x(i) = 'U') then
tmp(i):= '0';
else
tmp(i):=x(i);
end if; 
end loop; 
return tmp;
end function;
function "or" (left, right: t_obp_in_registers) return t_obp_in_registers is
variable tmp: t_obp_in_registers;
begin
tmp.cflags_prog_i := f_x_to_zero(left.cflags_prog_i) or f_x_to_zero(right.cflags_prog_i);
return tmp;
end function;
end package body;
