files = [	"endpoint_private_pkg.vhd",
                "ep_rx_pcs_8bit.vhd",
                "ep_tx_pcs_8bit.vhd",
                "ep_tx_pcs_16bit.vhd",
                "ep_rx_pcs_16bit.vhd",
                "ep_autonegotiation.vhd",
                "ep_pcs_tbi_mdio_wb.vhd",
                "ep_1000basex_pcs.vhd",
                "ep_rx_crc_size_check.vhd",
                "ep_rx_bypass_queue.vhd",
                "ep_rx_path.vhd",
                "ep_rx_wb_master.vhd",
                "ep_rx_oob_insert.vhd",
                "ep_rx_early_address_match.vhd",
                "ep_clock_alignment_fifo.vhd",
                "ep_tx_framer.vhd",
                "ep_packet_filter.vhd",
                "ep_rx_vlan_unit.vhd",
                "ep_ts_counter.vhd",
                "ep_rx_status_reg_insert.vhd",
                "ep_timestamping_unit.vhd",
  
#					"ep_flow_control.vhd",
#					"ep_timestamping_unit.vhd",
#					"ep_rmon_counters.vhd",
                "ep_rx_buffer.vhd",
                "ep_sync_detect.vhd",
                "ep_sync_detect_16bit.vhd",
                "ep_wishbone_controller.vhd",
                "ep_registers_pkg.vhd",
                "endpoint_pkg.vhd",
                "wr_endpoint.vhd",
                "xwr_endpoint.vhd"
                ];
