SRCS_VHDL = gtp_bitslide.vhd \
gtp_phase_align.vhd \
wr_gtp_phy_spartan6.vhd \
whiterabbitgtp_wrapper.vhd \
whiterabbitgtp_wrapper_tile.vhd

WORK = work

#directories in which we should search for the VHDL/verilog source files
VPATH =

include ../../scripts/modules.mk


