files = ["gtp_bitslide.vhd",
				 "gtp_phase_align.vhd",
				 "gtp_phase_align_virtex6.vhd",
				 "gtx_reset.vhd",
				 "whiterabbitgtx_wrapper_gtx.vhd",
#				 "whiterabbitgtp_wrapper.vhd",
				 "whiterabbitgtp_wrapper_tile.vhd",
         "whiterabbit_gtxe2_channel_wrapper_gt.vhd",
			"whiterabbit_gthe2_channel_wrapper_gt.vhd",
				 "wr_gtp_phy_spartan6.vhd",
				 "wr_gtx_phy_virtex6.vhd",
         "wr_gtx_phy_kintex7.vhd",
			"wr_gth_phy_virtex7.vhd"];
